services:
  fastapi:
    public: true
    image: deliveryklad/fastapi-crud:latest
    build: .
    replicas: 1
    environment:
      SECRET: $identity_secret
      DATABASE_URL: $identity_database
    ports:
      - 8080
    resources:
      cpu: 500m
      memory: 512Mi
